name: memogenerator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.7
  provider: ^6.0.4
  google_fonts: ^3.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.13.0

flutter:
  uses-material-design: true
