name: memogenerator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.1
  rxdart: ^0.28.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  dio: ^5.9.0
  either_dart: ^1.0.0
  image_picker: ^1.2.0
  path_provider: ^2.1.5           #НЕ ПОДДЕРЖИВАЕТ WEB
  image: ^4.5.4
  cached_network_image: ^3.4.1
  screenshot: ^3.0.0
  share_plus: ^11.1.0
  flutter_svg: ^2.2.0
  flutter_colorpicker: ^1.1.0
  yx_scope: ^1.1.2
  yx_scope_flutter: ^1.1.2
  yx_state: ^1.0.0
  yx_state_flutter: ^1.0.0
  yx_state_transformers: ^1.0.0
  talker: ^5.0.0
  talker_flutter: ^5.0.0
  talker_dio_logger: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.4.0
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  golden_toolkit: ^0.15.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
#  custom_lint: ^0.8.0
#  yx_scope_linter: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/platforms/
